import type { Metadata } from "next";
import "./globals.css";
import { Prata } from "next/font/google";

const prata = Prata({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "I Hate Small Talk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={prata.className}>{children}</body>
    </html>
  );
}
