import type { Metadata } from "next";
import { Cookie, Great_Vibes, Inter, Prata } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const great_Vibes = Great_Vibes({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-gv",
});

const prata = Prata({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-prata",
});
const cookie = Cookie({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cookie",
});

export const metadata: Metadata = {
  title: "I Hate Small Talk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={prata.className}>{children}</body>
    </html>
  );
}
